---
# This Github workflow will run jobs to build java-app.
name: dotnet-app

on:
  schedule:
  - cron: '0 0 * * *' # every night at 12:00AM UTC
  push:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_dispatch:
permissions:
  pull-requests: write

jobs:
  runs-on: [self-hosted, python, dotnet]
  minimal:
    uses: ploigos/ploigos-github-workflows/.github/workflows/minimal.yaml@main
    secrets: inherit
